CREATE OR REPLACE TABLE BRONZE.NETFLIX_TITLES AS
SELECT  
    SHOW_ID,
    "TYPE",
    LOWER(TITLE) AS TITLE,
    LOWER(CASE WHEN DIRECTOR = '' THEN 'N/A' ELSE DIRECTOR END) AS DIRECTOR,
    LOWER(CASE WHEN "CAST" = '' THEN 'N/A' ELSE "CAST" END) AS "CAST",
    LOWER(CASE WHEN COUNTRY = '' THEN 'N/A' ELSE COUNTRY END) AS COUNTRY,
    CASE 
        WHEN DATE_ADDED = '' THEN NULL 
        ELSE TO_DATE(TRIM(DATE_ADDED), 'MMMM DD, YYYY') 
    END AS DATE_ADDED,
    RELEASE_YEAR,
    LOWER(CASE WHEN RATING = '' THEN 'not_rated' ELSE RATING END) AS RATING,
    TRY_CAST(SPLIT_PART(DURATION, ' ', 1) AS INT) AS DURATION_VALUE,
    LOWER(SPLIT_PART(DURATION, ' ', 2)) AS DURATION_UNIT,
    LOWER(LISTED_IN) AS LISTED_IN,
    LOWER(DESCRIPTION) AS DESCRIPTION
FROM RAW.NETFLIX_TITLES;