-- DIMENSÕES --

CREATE OR REPLACE TABLE GOLD.DIM_LISTED_IN AS
SELECT DISTINCT
    LISTED_IN
FROM SILVER.NETFLIX_LISTED_IN;

CREATE OR REPLACE TABLE GOLD.DIM_COUNTRY AS
SELECT DISTINCT
    COUNTRY
FROM SILVER.NETFLIX_COUNTRY;

CREATE OR REPLACE TABLE GOLD.DIM_DIRECTOR AS
SELECT DISTINCT
    DIRECTOR
FROM SILVER.NETFLIX_DIRECTOR;

CREATE OR REPLACE TABLE GOLD.DIM_CAST AS
SELECT DISTINCT
    "CAST"
FROM SILVER.NETFLIX_CAST;

CREATE OR REPLACE TABLE GOLD.DIM_TITLES AS
SELECT DISTINCT
    SHOW_ID,
    TITLE,
    "TYPE",
    RATING,
    DATE_ADDED,
    RELEASE_YEAR
FROM SILVER.NETFLIX_TITLES;

CREATE OR REPLACE TABLE GOLD.DIM_SHOWS AS
SELECT DISTINCT
    SHOW_ID
FROM SILVER.NETFLIX_TITLES;

-- FATOS --

CREATE OR REPLACE TABLE GOLD.FACT_LISTED_IN_SHOW AS
SELECT
    *
FROM SILVER.NETFLIX_LISTED_IN;

CREATE OR REPLACE TABLE GOLD.FACT_COUNTRY_SHOW AS
SELECT
    *
FROM SILVER.NETFLIX_COUNTRY;

CREATE OR REPLACE TABLE GOLD.FACT_DIRECTOR_SHOW AS
SELECT
    *
FROM SILVER.NETFLIX_DIRECTOR;

CREATE OR REPLACE TABLE GOLD.FACT_CAST_SHOW AS
SELECT
    *
FROM SILVER.NETFLIX_CAST;
