CREATE OR REPLACE TABLE SILVER.NETFLIX_DIRECTOR AS
SELECT 
    SHOW_ID,
    TRIM(f.VALUE) AS DIRECTOR
FROM BRONZE.NETFLIX_TITLES,
LATERAL FLATTEN(input => SPLIT(DIRECTOR, ',')) AS f;


CREATE OR REPLACE TABLE SILVER.NETFLIX_COUNTRY AS
SELECT 
    SHOW_ID,
    TRIM(f.VALUE) AS COUNTRY
FROM BRONZE.NETFLIX_TITLES,
LATERAL FLATTEN(input => SPLIT(COUNTRY, ',')) AS f;


CREATE OR REPLACE TABLE SILVER.NETFLIX_LISTED_IN AS
SELECT 
    SHOW_ID,
    TRIM(f.VALUE) AS LISTED_IN
FROM BRONZE.NETFLIX_TITLES,
LATERAL FLATTEN(input => SPLIT(LISTED_IN, ',')) AS f;


CREATE OR REPLACE TABLE SILVER.NETFLIX_CAST AS
SELECT 
    SHOW_ID,
    TRIM(f.VALUE) AS "CAST"
FROM BRONZE.NETFLIX_TITLES,
LATERAL FLATTEN(input => SPLIT("CAST", ',')) AS f;

CREATE OR REPLACE TABLE SILVER.NETFLIX_TITLES AS
SELECT 
    SHOW_ID,
    TITLE,
    "TYPE",
    RATING,
    DESCRIPTION,
    DATE_ADDED,
    RELEASE_YEAR,
    DURATION_VALUE,
    DURATION_UNIT
FROM BRONZE.NETFLIX_TITLES;
